# /* Copyright 2023 MonographDB.
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *    http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
#  */

# Default values for monosql-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section Name parameters
## @param nameOverride String to partially override common.names.fullname template (will maintain the release name)
##
nameOverride: monosql-controller-manager
timezone: UTC
appendReleaseSuffix: false

## controller manager
controllerManager:
  serviceAccount: "monosql-operator-sa"
  image:
    repository: monographdb/monosql-operator:v1.0.0-nightly
    tag: v1.0.0-nightly
    pullPolicy: IfNotPresent
  ## In case the above image is pulled from a registry that requires
  ## authentication, a secret containining credentials can be added
  ## imagePullSecrets:
  ##   - secret_with_credentials_to_custom_registry
  imagePullSecrets: { }
  resources:
    requests:
      cpu: 2
      memory: "512Mi"
    limits:
      cpu: 2
      memory: 1G
  healthAddr: ":18081"
  metricsAddr: ":18080"
  healthPort: 18081
  env: [ ]
