apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if eq .Values.appendReleaseSuffix true}}
  name: monosql-controller-manager-{{.Release.Name }}
    {{- else }}
  name: monosql-controller-manager
    {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "monosql-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller-manager
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "monosql-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "monosql-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: controller-manager
    spec:
      serviceAccountName: {{ .Values.controllerManager.serviceAccount }}
      containers:
        - name: monosql-controller-manager
          image: {{ .Values.controllerManager.image.repository }}:{{ .Values.controllerManager.image.tag }}
          imagePullPolicy: {{ .Values.controllerManager.image.pullPolicy | default "IfNotPresent" }}
          command:
            - /manager
          args:
            - --metrics-bind-address={{ .Values.controllerManager.metricsAddr}}
            - --health-probe-bind-address={{ .Values.controllerManager.healthAddr}}
          ports:
            - name: healthcheck
              containerPort: {{ .Values.controllerManager.healthPort }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TZ
              value: {{ .Values.timezone | default "UTC" }}
                    {{- if eq .Values.appendReleaseSuffix true}}
                    {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.controllerManager.healthPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.controllerManager.healthPort}}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.controllerManager.resources | nindent 12 }}

      {{- with .Values.controllerManager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
